```{r}
df <- read.csv("ses_trans.csv")
df
demo <- read.csv("demographics_2014.csv")
demo
```
```{r}
library(dplyr)
library(ggplot2)
library(sqldf)
library(anytime)
library(plm)
library(tidyverse)
library(lubridate)
library(standardize)
library(data.table)
library(MatchIt)
library(gplots) 
library(gplots)
library(tseries)
library(lmtest)
library(car)
library(qwraps2)
library(magrittr)
library(broom)
library(stats)
library(gridExtra)
```
```{r}
df <- sqldf("SELECT *
            FROM df AS D
            LEFT JOIN demo AS DE
            ON D.machine_id = DE.machine_id")
df
```
```{r}
names(df)
```

```{r}
sum(is.na(df$prod_totprice))
df$prod_totprice[is.na(df$prod_totprice) == TRUE] <- mean(df$prod_totprice, na.rm = TRUE)
table(is.na(df$prod_totprice))
```

```{r}
sum(is.na(df$basket_tot))
df$basket_tot[is.na(df$basket_tot) == TRUE] <- mean(df$basket_tot, na.rm = TRUE)
table(is.na(df$basket_tot))
```
```{r}
names(df)
```
```{r}
df <- df %>%
  select(-c(ref_domain_name, tran_flg, event_time.x, event_time.y))
df
```
```{r}
df$prod_category_id <- factor(df$prod_category_id)
df$hoh_most_education <- factor(df$hoh_most_education)
df$census_region <- factor(df$census_region)
df$household_size <- factor(df$household_size)
df$hoh_oldest_age <- factor(df$hoh_oldest_age)
df$household_income <- factor(df$household_income)
df$children <- factor(df$children)
df$racial_background <- factor(df$racial_background)
df$connection_speed <- factor(df$connection_speed)
df$country_of_origin <- factor(df$country_of_origin)
df$zip_code <- factor(df$zip_code)
```

```{r}
df$Dummy_Duration <- ifelse(df$duration < 32.36,0,1)
df
```


```{r}
newdf <- df %>%
  transmute(machine_id,
            site_session_id,
            domain_id.x,
            pages_viewed_log = log(pages_viewed),
            duration_log = log(duration + 1),
            domain_name.x,
            prod_category_id,
            domain_id.y,
            prod_qty_log = log(prod_qty),
            prod_totprice_log = log(prod_totprice + 1),
            basket_tot_log = log(basket_tot + 1),
            event_date.y,
            event_time.y,
            domain_name.y,
            hoh_most_education,
            census_region,
            household_size,
            hoh_oldest_age,
            household_income,
            children,
            racial_background,
            connection_speed,
            country_of_origin,
            zip_code,
            Dummy_Duration)
newdf
```

```{r}
df_cov <- c("prod_qty_log","prod_totprice_log", "pages_viewed_log")
newdf %>%
  dplyr::group_by(Dummy_Duration) %>%
  dplyr::select(one_of(df_cov)) %>%
  dplyr::summarise_all(funs(mean(., na.rm = T)))
```

```{r}
m_ps <- glm(Dummy_Duration ~ pages_viewed_log + prod_totprice_log + prod_qty_log + prod_category_id + hoh_most_education + census_region + household_size + hoh_oldest_age + household_income + children + racial_background + connection_speed + country_of_origin, family = binomial(), data = newdf)
summary(m_ps)
```

```{r}
prs_df <- data.frame(pr_score = predict(m_ps, type = "response"),
                     duration = m_ps$model$Dummy_Duration)
head(prs_df)
```

```{r}
labs <- paste("People who:", c("have shorter duration", "have longer duration"))
prs_df %>%
  mutate(duration = ifelse(duration == 1, labs[1], labs[2])) %>%
  ggplot(aes(x = pr_score)) +
  geom_histogram(color = "white") +
  facet_wrap(~duration) +
  xlab("Probability of having Longer Duation") +
  theme_bw()
```

```{r}
highnotes_nomiss <- newdf %>%  # MatchIt does not allow missing values
  select(Dummy_Duration, one_of(df_cov)) %>%
  na.omit()

model_match <- matchit(Dummy_Duration ~ prod_qty_log + prod_totprice_log + pages_viewed_log, method = "nearest", data = highnotes_nomiss)
```
```{r}
summary(model_match)
plot(model_match)
```
```{r}
dta_m <- match.data(model_match)
dim(dta_m)
```

```{r}
fn_bal <- function(dta, variable) {
  dta$variable <- dta[, variable]
  dta$Dummy_Duration <- as.factor(dta$Dummy_Duration)
  support <- c(min(dta$variable), max(dta$variable))
  ggplot(dta, aes(x = distance, y = variable, color = Dummy_Duration)) +
    geom_point(alpha = 0.2, size = 1.3) +
    geom_smooth(method = "loess", se = F) +
    xlab("Propensity score") +
    ylab(variable) +
    theme_bw() +
    ylim(support)
}
```

```{r}
grid.arrange(
  fn_bal(dta_m, "prod_qty_log"),
  fn_bal(dta_m, "prod_totprice_log") + theme(legend.position = "none"),
  fn_bal(dta_m, "pages_viewed_log"),
  
  nrow = 2, widths = c(1, 0.8)
)
```
```{r}
# Difference of means
dta_m %>%
  group_by(Dummy_Duration) %>%
  select(one_of(df_cov)) %>%
  summarise_all(funs(mean(., na.rm = T)))
```
```{r}
t.test(newdf$basket_tot ~ newdf$Dummy_Duration)
```

```{r}
newdf %>%
  dplyr::group_by(Dummy_Duration) %>%
  dplyr::summarise(meansub = mean(basket_tot_log))
```

```{r}
dta_m %>%
  dplyr::group_by(Dummy_Duration) %>%
  dplyr::summarise(meansub = mean(basket_tot_log))
```